"""
Lite Research 常量定义
包含项目中使用的所有常量和魔法数字
"""

# 网络请求相关常量
DEFAULT_TIMEOUT = 4
DEFAULT_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"

# 并发和性能相关常量
DEFAULT_CONCURRENCY_LIMIT = 5
DEFAULT_MAX_WORKERS = 20
MIN_CONTENT_LENGTH = 100

# 模型和令牌相关常量
DEFAULT_TEMPERATURE = 0.55
DEFAULT_FAST_TOKEN_LIMIT = 4000
DEFAULT_SMART_TOKEN_LIMIT = 4000
DEFAULT_SUMMARY_TOKEN_LIMIT = 700
DEFAULT_BROWSE_CHUNK_MAX_LENGTH = 8192

# 搜索和检索相关常量
DEFAULT_MAX_SEARCH_RESULTS_PER_QUERY = 5
DEFAULT_MAX_ITERATIONS = 5
DEFAULT_MAX_SUBTOPICS = 5
DEFAULT_SIMILARITY_THRESHOLD = 0.38
DEFAULT_TOTAL_WORDS = 800

# 文本处理常量
CHUNK_SIZE = 500
CHUNK_OVERLAP = 100
MIN_QUERY_LENGTH = 3

# 报告格式常量
DEFAULT_REPORT_FORMAT = "APA"

# 嵌入和向量相关常量
DEFAULT_EMBEDDING_PROVIDER = "openai"
DEFAULT_MEMORY_BACKEND = "local"

# 检索器相关常量
DEFAULT_RETRIEVER = "tavily"
DEFAULT_SCRAPER = "bs"

# Langfuse 相关常量
DEFAULT_LANGFUSE_HOST = "https://cloud.langfuse.com"

# 验证限制常量
MAX_ITERATIONS_LIMIT = 10
MAX_SUBTOPICS_LIMIT = 10
MAX_SEARCH_RESULTS_LIMIT = 20
MIN_ITERATIONS = 1
MIN_SUBTOPICS = 1
MIN_SEARCH_RESULTS = 1 